/**
 * Apply the fixed Thai-name slugs from /tmp/slugmap.json to the clinics table,
 * and emit a Cloudflare Pages _redirects file mapping every old URL → new URL (301).
 *
 * Idempotent: each UPDATE is guarded on the current slug, so re-running is safe.
 *
 * Usage:
 *   npx tsx --env-file=.env.local scripts/apply-thai-slug-map.ts --dry-run
 *   npx tsx --env-file=.env.local scripts/apply-thai-slug-map.ts
 */
import { createClient } from "@libsql/client";
import { readFileSync, writeFileSync, existsSync } from "fs";
import path from "path";

type MapRow = {
  id: number;
  old_path: string;
  new_path: string;
  old_slug: string;
  new_slug: string;
  db_old_slug: string;
};

const DRY_RUN = process.argv.includes("--dry-run");
const REDIRECTS_PATH = path.resolve("public/_redirects");

async function main() {
  const map: MapRow[] = JSON.parse(readFileSync("/tmp/slugmap.json", "utf8"));
  const client = createClient({
    url: process.env.TURSO_URL!,
    authToken: process.env.TURSO_AUTH_TOKEN!,
  });

  // --- 1. Apply slug updates ---
  let updated = 0;
  let skipped = 0;
  for (const m of map) {
    if (DRY_RUN) {
      console.log(`  ${m.id}: ${m.old_slug} → ${m.new_slug}`);
      continue;
    }
    const res = await client.execute({
      sql: "UPDATE clinics SET slug = ?, updated_at = ? WHERE id = ? AND slug = ?",
      args: [m.new_slug, new Date().toISOString().slice(0, 10), m.id, m.old_slug],
    });
    if (res.rowsAffected > 0) updated++;
    else skipped++;
  }
  console.log(`\nDB: ${updated} updated, ${skipped} skipped (already migrated / no match).`);

  // --- 2. Generate/merge _redirects (idempotent, keyed by old path) ---
  const newLines = map.map((m) => `${m.old_path} ${m.new_path} 301`);

  // Preserve any pre-existing non-Thai-slug redirect lines.
  let preamble: string[] = [];
  const managedKeys = new Set(map.map((m) => m.old_path));
  if (existsSync(REDIRECTS_PATH)) {
    const existing = readFileSync(REDIRECTS_PATH, "utf8").split("\n");
    preamble = existing.filter((line) => {
      const src = line.trim().split(/\s+/)[0];
      return src && !line.startsWith("#") && !managedKeys.has(src);
    });
  }

  const header = "# Thai-name slug fixes — old → new, 301 (generated by apply-thai-slug-map.ts)";
  const body = [...preamble.filter((l) => l.trim()), header, ...newLines].join("\n") + "\n";

  if (DRY_RUN) {
    console.log(`\n--- _redirects preview (${newLines.length} lines) ---`);
    console.log(newLines.slice(0, 5).join("\n"));
    console.log("...");
    return;
  }

  writeFileSync(REDIRECTS_PATH, body);
  console.log(`Wrote ${newLines.length} redirect lines → ${REDIRECTS_PATH}`);

  // --- 3. Verify no remaining old slugs in DB ---
  const oldSlugs = map.map((m) => m.old_slug);
  const placeholders = oldSlugs.map(() => "?").join(",");
  const check = await client.execute({
    sql: `SELECT id, slug FROM clinics WHERE slug IN (${placeholders})`,
    args: oldSlugs,
  });
  if (check.rows.length > 0) {
    console.log("\n⚠ Remaining old slugs still in DB:");
    check.rows.forEach((r) => console.log(`  ${r[0]}: ${r[1]}`));
  } else {
    console.log("✓ No old Thai slugs remain in DB.");
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
